export const instructors = [
  {
    abbreviation: 'VMS',
    fullName: 'วีระ เหมืองสิน',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'NNN',
    fullName: 'นัทที นิภานันท์',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'KPR',
    fullName: 'เกริก ภิรมย์โสภา',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'KSC',
    fullName: 'กุลวดี ศรีพานิชกุลชัย',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'NNP',
    fullName: 'ณัฐวุฒิ หนูไพโรจน์',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'KRC',
    fullName: 'กุลธิดา โรจน์วิบูลย์ชัย',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'YLK',
    fullName: 'ญาใจ ลิ่มปิยะกรณ์',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'PSC',
    fullName: 'พรรณราย ศิริเจริญ',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'ATT',
    fullName: 'อาทิตย์ ทองทักษ์',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'SSY',
    fullName: 'สุกรี สินธุภิญโญ',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'PKY',
    fullName: 'พิศณุ คนองชัยยศ',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'DWK',
    fullName: 'ดวงดาว วิชาดากุล',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'PKV',
    fullName: 'พิตติพล คันธวัฒน์',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'JTP',
    fullName: 'เจษฎา ธัชแก้วกรพินธุ์',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'ASR',
    fullName: 'อรรถสิทธิ์ สุรฤกษ์',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'ATS',
    fullName: 'อรรถวิทย์ สุดแสง',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'AST',
    fullName: 'อติวงศ์ สุชาโต',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'PJW',
    fullName: 'ประภาส จงสถิตย์วัฒนา',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'VKJ',
    fullName: 'วิษณุ โคตรจรัส',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'PVK',
    fullName: 'พีรพล เวทีกูล',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'WWW',
    fullName: 'วิวัฒน์ วัฒนาวุฒิ',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'TRD',
    fullName: 'ธงชัย โรจน์กังสดาล',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'NCN',
    fullName: 'ณัฐพงศ์ ชินธเนศ',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'NKN',
    fullName: 'ณรงค์เดช กีรติพรานนท์',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'WSR',
    fullName: 'วริษา ศรีไตรรัตนรักษ์',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'PSA',
    fullName: 'พิชญะ สิทธีอมร',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'SPN',
    fullName: 'เศรษฐา ปานงาม',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'PPN',
    fullName: 'โปรดปราน บุณยพุกกณะ',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'NTR',
    fullName: 'เนื่องวงศ์ ทวยเจริญ',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'TSS',
    fullName: 'ธาราทิพย์ สุวรรณศาสตร์',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'CRN',
    fullName: 'โชติรัตน์ รัตนามหัทธนะ',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'NPP',
    fullName: 'นครทิพย์ พร้อมพูล',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'TSV',
    fullName: 'ทวิตีย์ เสนีวงศ์ ณ อยุธยา',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'ECN',
    fullName: 'เอกพล ช่วงสุวนิช',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'MOT',
    fullName: 'มัชฌิกา อ่องแตง',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'SRS',
    fullName: 'สุธี เรืองวิเศษ',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'BKK',
    fullName: 'บุญเสริม กิจศิริกุล',
    faculty: 'Engineering',
    department: 'Computer Engineering',
  },
  {
    abbreviation: 'JCR',
    fullName: 'จิรวัฒน์ ชีวรุ่งโรจน์',
    faculty: 'Engineering',
    department: 'Petroleum Engineering',
  },
  {
    abbreviation: 'KJK',
    fullName: 'กิตติพงค์ จงกิตตินฤกร',
    faculty: 'Engineering',
    department: 'Petroleum Engineering',
  },
  {
    abbreviation: 'KMI',
    fullName: 'เกรียงไกร มณีอินทร์',
    faculty: 'Engineering',
    department: 'Petroleum Engineering',
  },
  {
    abbreviation: 'FSC',
    fullName: 'ฟ้าลั่น ศรีสุริยชัย',
    faculty: 'Engineering',
    department: 'Petroleum Engineering',
  },
  {
    abbreviation: 'TCR',
    fullName: 'ทศพล ไชยอนันต์สุจริต',
    faculty: 'Engineering',
    department: 'Petroleum Engineering',
  },
  {
    abbreviation: 'CTT',
    fullName: 'จิตติน แตงเที่ยง',
    faculty: 'Engineering',
    department: 'Mechanical Engineering',
  },
  {
    abbreviation: 'PSG',
    fullName: 'ไพโรจน์ สิงหถนัดกิจ',
    faculty: 'Engineering',
    department: 'Mechanical Engineering',
  },
  {
    abbreviation: 'NAP',
    department: 'Statistics',
    faculty: 'Commerce And Accountancy',
    fullName: 'Narongrid Asavaroungpipop',
  },
  {
    abbreviation: 'TCB',
    department: 'Computer Engineering',
    faculty: 'Engineering',
    fullName: 'Thanarat Chalidabhongse',
  },
  {
    abbreviation: 'CNP',
    department: 'Computer Engineering',
    faculty: 'Engineering',
    fullName: 'Chate Patanothai',
  },
  {
    abbreviation: 'WWS',
    department: 'Mechanical Engineering',
    faculty: 'Engineering',
    fullName: 'วิทยา วัณณสุโภประสิทธิ์',
  },
  {
    abbreviation: 'KMN',
    department: 'Mechanical Engineering',
    faculty: 'Engineering',
    fullName: 'กุณฑินี มณีรัตน์',
  },
];
