on:
  issues:
    types: [opened]
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  pr:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'issues' ||
      (github.event_name == 'pull_request' && startsWith(github.event.pull_request.head.ref, 'instructor-abbreviation/'))
    steps:
      - name: Validate issue title
        run: |
          TITLE="${{ github.event.issue.title }}"
          if ! echo "$TITLE" | grep -q 'Instructor Abbreviation:'; then
            echo "::error::Issue title must start with \"Add Instructor Abbreviation:\" or \"Update Instructor Abbreviation:\""
            exit 1
          fi

      - name: Generate GitHub App Token
        uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Check for any open instructor-abbreviation PRs
        run: |
          echo "Checking for open PRs with branch name starting with instructor-abbreviation/"

          OPEN_PR=$(gh pr list --state open --json number,headRefName,title \
            --jq '.[] | select(.headRefName | startswith("instructor-abbreviation/"))')

          if [ -n "$OPEN_PR" ]; then
            echo "$OPEN_PR" | jq -c '.'
            echo "::error::Another instructor-abbreviation PR is still open. Please wait until it is merged or closed."
            exit 0
          fi

          echo "No conflicting open PRs found. Proceeding..."
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          token: ${{ steps.generate-token.outputs.token }}

      - name: Setup Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.11.0
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Set git to use HTTPS instead of SSH for github.com
        run: git config --global url."https://github.com/".insteadOf "git@github.com:"

      - name: Install dependencies
        run: pnpm install

      - name: Update
        run: npx tsx scripts/update_instructor.ts
        env:
          BODY: '${{ github.event.issue.body }}'

      - name: Format
        run: npx prettier --write src/db/data.ts

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: 'Add or Update Instructor Abbreviation from issue #${{ github.event.issue.number }}'
          committer: Jarn-Nai[bot] <1505243+Jarn-Nai[bot]@users.noreply.github.com>
          title: 'Automated ${{ github.event.issue.title }}'
          body: |
            This PR was automatically generated in response to issue #${{ github.event.issue.number }}.

            **Summary of changes:**
            - ${{
                github.event.issue.title
              }}

            Please review the changes to `src/db/data.ts` and ensure the instructor abbreviation information is correct.
          branch: instructor-abbreviation/${{ github.event.issue.number }}
          delete-branch: true
          add-paths: |
            src/db/data.ts
          labels: |
            🧑‍🏫 instructor
          reviewers: |
            yokeTH
            Thiraput01
